name: nodeCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: cd .\testReactTruffle\client
    - run: npm install
    - run: npm run build
    - run: cd ..
    - run: cd ..
    - run: xcopy C:\GitHubRepos\GitHub\Simple-React-Dapp\testReactTruffle\client\build C:\GitHubRepos\GitHub\Simple-React-Dapp\docs /e /i /y /v
    